### ISSUE TITLE
WebSockets

### ISSUE THREAD

**Issue by mnot** [httpwg/http2-spec#386]
This issue is a placeholder / tracking issue for anything related to WebSockets support in HTTP/2.

**Comment by ApfelUser** [comment]
Are there any updates on this? It has been a whole year now since someone commented on this, are WebSockets still going to be implemented in **HTTP/2**?

**Comment by MartinKei** [comment]
What's the status on this one?

**Comment by martinthomson** [comment]
Awaiting someone to do some work: implement it, convince others to implement it, etc...

**Comment by AlanQuatermain** [comment]
I'm looking into this for the HTTP/2 upgrade across our systems at LinkedIn. I'm given to understand that the lack of WebSockets makes this upgrade more arduous for us (i.e. minimal benefit unless we roll out these changes across a very wide number of micro services across a large number of colocation locations, etc.) I've found Yutaka Hirano's [draft spec at the IETF](https://tools.ietf.org/html/draft-hirano-httpbis-websocket-over-http2-01) and it looks like I can take that & run with it fairly simply.

My question here is: who else is interested in this? Has there been any other work in this direction since Hirano's last draft nearly three years ago?

**Comment by bagder** [comment]
@AlanQuatermain: there's now a new draft [being discussed](https://lists.w3.org/Archives/Public/ietf-http-wg/2017OctDec/thread.html) and worked on in the HTTPbis WG: https://datatracker.ietf.org/doc/draft-mcmanus-httpbis-h2-websockets/
