### ISSUE TITLE
Integrate TLS 1.3 updates

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http2-spec#774]
A few small changes are included in [RFC 8740](https://tools.ietf.org/html/rfc8740), which could be integrated easily.

**Comment by martinthomson** [comment]
I won't create the pull request just yet, but here are some proposed changes: https://github.com/martinthomson/http2v2/pull/new/tls13

@davidben, do you think that you could review these?  I've paraphrased some of RFC 8740 and I want to make sure I haven't missed anything.

**Comment by davidben** [comment]
(The GitHub link did something silly, but I'm assuming 837d46a5ff9e23a62cb719f69be7f1d10bf8da80 is the right commit and just looked at that.)

>  TLS 1.3 does not permit renegotiation, so the exception permitting renegotiation before sending the preface the handshake does not apply.

s/the handshake//
Though I wonder if this sentence can just be omitted. I needed to address it in RFC8740 because RFC7540 didn't have a TLS version dispatch. But now the TLS 1.2 features section is explicitly mentioned as being 1.2-only, so that exception already doesn't apply.

Otherwise LGTM. (I think the default values in server settings is implicit from the fact that we haven't received anything from the server yet, but whatever.)

**Comment by martinthomson** [comment]
Thanks.  I've updated my branch to remove the renegotiation piece.  I've updated that link (which I should have checked).
