### ISSUE TITLE
Try to improve the definition of the closed state

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http2-spec#783]
Rules around the closed state are particularly ambigous, because we lack a "closing" or equivalent state and any forced local close by RST_STREAM results in incoming frames violating the rules for what is acceptable in closed state since the other end doesn't know it's closed. It used to be even more problematic with priorities since some dependencies could be completely changed. I had a proposal to improve this using a form of ACK for RST/GOAWAY using PING that would allow one side to know when the other side was notified of these frames, but with priorities gone I don't think that's needed anymore. However we still need to be careful about the MUST NOT wording around whatever involves the closed state.

Suggested by @wtarreau.

**Comment by Lukasa** [comment]
Agreed to this, I keep track with a bit of whether _we_ forcibly reset the stream or whether the remote peer did, and give the remote peer some grace if we did. Seems like this is what everyone has to do, but new text might be nice.

**Comment by martinthomson** [comment]
We *could* split the states into two.  It's a little disruptive, but there are just 14 mentions of "closed" in the document currently, and a change like this would definitely remove one of those.

The definition would be:
* On sending RST_STREAM on a stream in the "open", "half-closed (remote)", or "reserved (local)" states, the stream becomes "reset".  In this state, you accept frames as though the stream were "open", but aside from PUSH_PROMISE, frames can be ignored.  PUSH_PROMISE frames in this state cause the promised stream to be reserved as normal, these have to be reset if they are not wanted.
* On receiving RST_STREAM on a stream in the "open", "half-closed (local)", "reserved (remote)", or "reset" states, the stream becomes "closed".  Any frames received on this stream in this state are treated as being in error.

Sending and receiving frames with END_STREAM set don't change: they cause a transition to "closed" (or one of the "half-closed" states) as before.

The diagram gets a little ugly though...

```
                             +--------+
                     send PP |        | recv PP
                    ,--------|  idle  |--------.
                   /         |        |         \
                  v          +--------+          v
           +----------+          |           +----------+
           |          |          | send H /  |          |-------.
   ,-------| reserved |          | recv H    | reserved |       |
   |       | (local)  |          |           | (remote) |-----. |
   |       +----------+          v           +----------+     | |
   |           |             +--------+             |         | |
   |           |     recv ES |        | send ES     |         | |
   |    send H |     ,-------|  open  |-------.     | recv H  | |
   |           |    /        |        |        \    |         | |
   |           v   v         +--------+         v   v         | |
   |       +----------+         |   |          +----------+   | |
   |       |   half   |         |   |          |   half   |   | |
   |       |  closed  |         |   |          |  closed  |   | |
   |       | (remote) |         |   | send R   | (local)  |   | |
   |       +----------+         |   v          +----------+   | |
   |           |                | +-------+       |    |      | |
   |           |                | |       |<------'    |      | |
   |           |         recv R | | reset |  send R    |      | |
   |           |                | |       |<-----------(-----'  |
   |           |                | +-------+  send R    |        |
   |           |                |   |                  |        |
   |           |                |   | recv R           |        |
   |           | recv ES /      |   |                  |        |
   |           | send R /       v   v        recv ES / |        |
   |           | recv R      +--------+      recv R    |        |
   | recv R /  `------------>|        |<---------------'        |
   | send R                  | closed |                  recv R |
   `------------------------>|        |<------------------------'
                             +--------+
```

**Comment by wtarreau** [comment]
This could help but an issue remains that a stream can stay forever in reset state because there's no automatic transition to close (no regular traffic, timers nor counters). One possible approach could be to state that after SETTINGS_MAX_CONCURRENT_STREAMS new streams, a reset stream automatically becomes closed. This would avoid keeping infinite amount of resources and avoid relying on a timer. Instead, each end would only keep a fixed size list of streams, and each new one would simply push the oldest reset one out so there wouldn't be any specific bookkeeping to be performed here.

I don't see this change as a radical one and the diagram doesn't look more complicated to me. It would be nice to get Cory's opinion on this since he's faced similar issues.

**Comment by wtarreau** [comment]
Also, thinking about it a bit more, my initial proposal consisting in sending a PING frame after an RST to detect when it had been received is implicitly covered by this mechanism of counting streams, because for the client to initiate as many streams, it proves it has been aware of at least as many closures, hence it received the RST. So that makes the approach even more interesting than my initially proposed one because we don't need to touch anything on the wire and we can still infer the fact that the other end received our RST.

So we have everything to help implementations optionally improve if they're interested in this!

**Comment by Lukasa** [comment]
I agree with @wtarreau that the change to the state diagram and state machine is pretty minor. It doesn't add unnecessary complexity.

What does require thought is the question of automatic transition from "reset" to "closed". Timers are a bit less than ideal, though if you've got reasonable estimates for the round-trip delay you can arrange a _very_ high fidelity timer for dropping your state.

The idea of tombstoning the streams is also pretty good. The problem with "push the oldest reset one out" isn't a protocol problem but an implementation problem, which is that a data structure optimised for that use-case is a bit awkward. In most cases the number of concurrent streams on any connection is low so the operation is fairly cheap but it's still not ideal.

You can make this a lot cheaper (and we do) by, when resetting a stream, dropping all stream state immediately except for the stream identifier. This lets us throw away our expensive-to-maintain state and retain just enough to ignore the inbound frames. This does expose us to a small period of time where we don't have the capacity to enforce several of the MUSTs in the RFC, but it's more important to us to preserve and minimise our state commitment than to police, say, the flow control window of a stream we don't have anymore.

I think perhaps the best step is to provide a range of guidance in a "state management" section. We don't have this today, but it's probably useful to add. The guidance can be:

1. When resetting a stream, you transition the stream to the reset state. This state requires keeping around some amount of stream data in order to identify and tolerate frames on that stream.
2. You can drop this state at your own leisure, but it SHOULD last at least as long as one complete RTT, to allow the peer to process the reset.
3. There are a few ways to know that this time has passed:
    1. If you have access to an accurate estimate of the RTT (e.g. via PING frames) you can set a timer.
    2. If you see SETTINGS_MAX_CONCURRENT_STREAMS new streams created since the reset, you can drop the stream.
    3. If you send and get get a response to a PING frame you can drop the stream.
    4. If you send and get a response to a SETTINGS frame you can drop the stream.
    5. If you create a new stream and receive any frame on it you can drop the stream.

Implementers are however free to implement this logic in whatever way is best for their implementation.

How does this seem?

**Comment by wtarreau** [comment]
I'm pretty fine with this, and your enumeration of the various ways to infer the round trip are sound and correct, and they give good guidance to implementations.

+1 for me :-)

**Comment by martinthomson** [comment]
I think that you both have a higher tolerance for complexity than I do.  That said, it's probably worth doing something in the spec to manage this more cleanly.

Like Cory, I was thinking that there are plenty of ambient signals you might use to garbage collect reset streams.  Basically anything you send after the RST that has an HTTP/2-level acknowlegment would do.  The list above seems right, though the RTT thing is fraught so I'd drop that.

On the other hand, I wouldn't be surprised if many existing implementations simply ignore the set of frames that a reset stream might receive for any closed stream.  That's not a terrible response to this problem.  There is no additional state involved and it is very much simpler.  It doesn't catch people violating the spec, but we don't all have to sign up for the protocol police.

Maybe the way to rephrase this is to make the lenient thing the primary thing, and then say...

An endpoint MAY close a connection if you detect a peer sending frames for a "closed" stream if either:
1. The peer has sent a frame on the stream with the END_STREAM flag set
2. The peer has sent RST_STREAM on the stream.
3. This endpoint closed the stream with RST_STREAM and other signals confirm that peer has definitely received the RST_STREAM frame.  This can be detected by: \<list the above ii..v\>

**Comment by Lukasa** [comment]
That would work for me, and we can add a little clause that says "or any other appropriate signal".

**Comment by wtarreau** [comment]
LGTM as well. Maybe then we should suggest that during this probation period the endpoint should avoid sending RST_STREAM for each received frame of this stream, but I seem to remember there's already a paragraph suggesting to moderate the amount of RST_STREAM emitted.
