### ISSUE TITLE
Speak a bit more about head-of-line blocking

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http2-spec#784]
H2 strongly suffers from head-of-line blocking when streams do not progress at the same spead, typically when they come from coalesced connections from different clients. Per-stream flow control is generally ineffective against this as practical window sizes matching a BDP often require impractical buffering between the intermediary and the client. As such we should mention in the recommendations that intermediaries that coalesce connections either have very large buffers or try to group streams from a same client connection together on a server connection.

Suggested by @wtarreau.

**Comment by martinthomson** [comment]
I'm not sure that I'm following the problem statement very well, so I'm not sure what sort of recommendation would go with it.

Is the problem that when aggregating requests from multiple clients you expose all of those clients - and all of the requests on the corresponding connections - to head-of-line blocking on the shared connection?  That doesn't seem quite right to me - though the requests that share that connection might suffer, the way that a stalled request on one connection might affect other requests on a different connection is limited.

If a request affects others, is it because it would consume shared resources like flow control window and connection-level flow control?  Keeping per-stream flow control relatively small relative to the connection limits would be the way to avoid that exposure, would it not?  That said, larger connection-level buffers might reduce contention, but in general more buffering just means more latency.

@wtarreau, am I chasing the right idea?  Maybe you can provide a paragraph on the problem and I can try to massage it into shape for the draft.

**Comment by wtarreau** [comment]
The issue is that the intermediary that coalesces many client connections into a single H2 connection cannot have infinite resources to buffer store the response data for these clients, yet will have to advertise a significantly large stream window to the other end to maintain an acceptable bandwidth. In practice it most often goes well because your advertised window is lower than what can be stored into system buffers. But once a client stalls, all the chain stalls, and you quickly end up in a situation where the advertised stream window is ahead of what you're really able to store.

Note that looking at how TCP buffers are filled in front is not always effective. You may very well be using H2 on the front with other streams making it hard to figure how much you could really push, you could have SSL under it having its own buffers, you could be applying compression in the middle, also making it hard to figure how much the output gives you on input, etc.

In haproxy we've finally adressed this by deciding that *by default* multiple clients are not coalesced over a server-facing H2 connection. We have multiple strategies of connection reuse so this remains configurable, but this was the best compromise we could find.

**Comment by wtarreau** [comment]
Probably that we could propose something like this:
```
Implementations that coalesce multiple individual clients' connections over a single H2 connection should be careful to properly adjust the per-stream window so that in no situation the sudden stop of a client requesting a large object results in blocking the transfer. This means the stream windows should never be larger than the total amount of per-stream storage the implementation may allocate to extract contents from the connection's buffers. If determining a sane threshold is not possible, implementations might prefer not to coalesce multiple clients on the same connection.
```

Also, please note that the same situation happens the other way around, with multiple uploads over a single H2 connection to multiple servers behind working at different speeds. It's generally less of an issue though, but the large windows necessary to permit fast POST uploads may very well block the retrieval of small objects by the same client within the same connection.

**Comment by martinthomson** [comment]
Is this just an over-commitment of flow control then?  That is, you advertise a window of N when you only really have space for M < N?

What is interesting is the implication here that you might be forced to advertise the larger window because if you don't you can't get decent throughput, but to do so you are betting that most of that capacity will be used by in-network state (data that is on the wire or in routers and whatnot, along with all the in-system buffers you don't see).  Of course, if that stalls, all that stuff in those buffers will all be forced into your buffers.  That can affect all connections that are somehow entangled with the affected stream.  That means all requests on the same connection, but it could affect other connections.

All that said, that's much more involved than your text here.  You appear to be looking for something much simpler.

We should have advice about the connection-level flow control credit being backed by real resources.  You say stream, but the purpose of connection-level flow control is to limit resource allocation.  While the stream-level values more directly determine stream-level throughput, the general idea is that they can be set with minimal regard to resource management if there is a good connection-level limit (the main consequence of not jointly managing these is a range of complicated priority issues).

The current document is not very good about saying much about any of this.  So any addition along these lines, including a version of that text, would be worth adding.

**Comment by grmocg** [comment]
When flow-control is set to values that the endpoint will respect, it
minimizes retransmits due to buffer overruns.
Minimizing retransmits does not always guarantee highest bandwidth; The
more conservative one is with respect to preventing retransmits or buffer
overruns, the more probable it is that some resources will be unused.
This is similar to the tradeoff space of congestion control, however the
buffers here are visible to the endpoints.

**Comment by wtarreau** [comment]
The thing is that due to the window-in-window you don't even benefit from the outer buffering (including the wire) if you have too small stream windows. With a single stream (or even H1) this problem does not exist at all as TCP acks at the edge. Here it's different, the data need to be delivered to userland and wait for its turn before the window can open again. I've seen POST requests slow down to 1 Mbps where the equivalent in H1 were 20 times higher using the same buffer size and TCP stack. So users bump the advertised window to compensate for this horrible performance and face random trouble. And on the server side the issue is the same but less visible, it mostly appears when the coalescing gateway and the servers are located on different datacenters a few milliseconds apart. But even at 4 ms with 64k windows it's only 128 Mbps per stream, so you can be sure that users are quite tempted to increase this for certain use cases where they see their devices twiddling thumbs on their 10/40/100G NICs. This is where it is possible to use the whole pipe's length when it's reserved or all streams of a given connection.

What I'm seeking is not to fix the protocol, it is how it is and we all knew about this limitation during its design, but rather to warn users against the risks and effects of not accurately calculating the advertised stream window size in case of combined streams.

**Comment by wtarreau** [comment]
By the way, one easy trap to fall into is to advertise a window corresponding to the buffer used at the connection level, while what matters is how much you can extract from this connection to be able to immediately parse subsequent frames. And often you have no precise ideas of how much space there is outside.

**Comment by martinthomson** [comment]
Let's try to pull something in, maybe copy from QUIC: https://quicwg.org/base-drafts/rfc9000.html#name-flow-control-performance
