### ISSUE TITLE
New ALPN protocol identifier for the revised protocol

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http2-spec#787]
@ianswett suggests:

A substantial number of deployed clients and servers do not support the extensibility of SETTINGs or frames in HTTP/2. It may be preferable to mint a new alpn for HTTP2v2 rather than trying to exclude all these peers based on user-agent or other fingerprinting.

For existing implementations, this has relatively low cost and greatly reduces deployment risk. At some point, they can drop support for the old h2 alpn and let clients fall back to HTTP 1.1, just like many did when SPDY support was removed.

More discussion at https://github.com/martinthomson/http2v2/issues/17

**Comment by wtarreau** [comment]
The ALPN string can land in user-visible configuration so that's not always transparent. Another option would be to maintain a backwards compatibility for the first round trip. E.g. see RFC8441, the client will not try to send WS before seeing explicit support for `:protocol`. Sure we can't upgrade everything and certain improvements will require a new ALPN. But if we find a way without this it's better, and our task it to spend a bit more brain time and efforts to save much hassle for implementations and end users.

**Comment by MikeBishop** [comment]
`h2.1`?

**Comment by mnot** [comment]
It doesn't appear we have the will to remove Server Push or Priorities (so far), so the only thing that _might_ motivate a new ALPN identifier is if we believe that `h2` has ossified enough to justify one (in order to introduce grease).

We don't necessarily need to make a final decision about this now, but it seems like we're leaning towards starting h2bis with the idea that we won't be introducing a new ALPN identifier. Does that make sense?

**Comment by ianswett** [comment]
I'd like to gather as much data as possible about how ossified we are at the moment before making a call.  Can others provide data in addition to the data Bence shared on the list?

OT: Can someone add Bence to this Github, I can't seem to link to him.

**Comment by wtarreau** [comment]
"ossified" as in "explicitly added by users in configuration files", sure, but then we'd really cause breaking changes annoying users just for the purpose of telling them "we wanted to be sure you were able to change this entry in your file".  For me changing the ALPN identifier is needed only if we want to make important protocol changes that are not compatible with the waste of a round trip to learn them via settings.

**Comment by ianswett** [comment]
I meant "ossified" as in every time we try to deploy a new SETTING or frame server-side it breaks a substantial fraction of users and we have to roll it back.  This is the reality I live in today.

**Comment by LPardue** [comment]
What does changing the ALPN ID mean for something like https://tools.ietf.org/html/rfc8164? Would a server have to start adverting both versions?

**Comment by martinthomson** [comment]
Yes, the effect is that Alt-Svc would need extra entries, whether it is for shifting load or opportunistic upgrade.

**Comment by mnot** [comment]
Discussed in Feb 2021 interim; bar is still high, waiting for a reason to do this to gain consensus.
