### ISSUE TITLE
Consider loosening requirement for clients to reject connection-specific header fields

### ISSUE THREAD

**Issue by jyasskin** [httpwg/http2-spec#789]
I have no personal knowledge of this issue, but it came up on the #whatwg IRC channel. https://megamorf.gitlab.io/2019/08/27/safari-nsposixerrordomain-100-error-with-nginx-and-apache/ describes Safari rejecting responses that contain the `upgrade` header field, while other browsers accept it. It'd be good to converge the major clients on a single behavior and, if that's not the behavior currently specified, update the spec to match.

**Comment by mnot** [comment]
To be clear, that's nginx being spectacularly broken by forwarding the `Upgrade` header field. 

I'd characterise the philosophy of H2 as being strict with errors that endanger the whole connection -- and counts the server asking for an upgrade in a context where it doesn't make sense as qualifying as such. 

While I'd be surprised if folks wanted to relax the former (the strictness is a net win for H2), the latter might be worth revisiting, not because nginx is broken, but because H1's use of headers for connection-level mechanisms turned out to be so broken. 

I'm also not sure that aligning all clients to be so permissive is such a great idea; accommodating brokenness like this is a race to the bottom, and while it might be the only practical path when you have to interoperate with a large and extremely diverse pool of existing deployment (HTML), there aren't *that* many HTTP implementations that can move the needle. Interop might be better served by holding the line and forcing broken servers to address their problems.

**Comment by hsivonen** [comment]
> To be clear, that's nginx being spectacularly broken by forwarding the `Upgrade` header field.

Additionally, it seems broken for Apache to send the `Upgrade` header when the connection between nginx and Apache is over TLS.

**Comment by hsivonen** [comment]
Filed [nginx bug](https://trac.nginx.org/nginx/ticket/2078).

**Comment by hsivonen** [comment]
[Looks like](https://bz.apache.org/bugzilla/show_bug.cgi?id=59311#c9) Apache treats the effects of sending `Upgrade` over TLS as a UA-side bug. :-(

**Comment by martinthomson** [comment]
Yeah, this looks bad.  The spec is fairly unambiguous about the requirement to ignore Upgrade in one place.  But it also prohibits the use of Connection, which implies that you can't use Upgrade.

I think that we should fix this, potentially along with #772.  I hope that we are able to convince @icing to change Apache here.  There is no value in sending this value.

**Comment by bazzadp** [comment]
FYI analysis, [I undertook of this last year](https://almanac.httparchive.org/en/2019/http2#http2-issues)

> 108 sites use HTTP/2 while they also suggest upgrading to HTTP/2 in the upgrade header. A further 12,767 sites on desktop (15,235 on mobile) suggest upgrading an HTTP/1.1 connection delivered over HTTPS to HTTP/2 when it's clear this was not available, or it would have been used already. These are a small minority of the 4.3 million sites crawled on desktop and 5.3 million sites crawled on mobile, but it shows that this is still an issue affecting a number of sites out there. Browsers handle this inconsistently, with Safari in particular attempting to upgrade and then getting itself in a mess and refusing to display the site at all.
