### ISSUE TITLE
"Payload" is too heavily overloaded

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http2-spec#803]
See https://github.com/httpwg/http-core/issues/654

**Comment by Lukasa** [comment]
I don't think we'll be editorialising here about what exactly we use instead of "payload body": that's for the core spec to choose and we'll follow. However, it would be beneficial to reconcile our uses of the word "payload" in preparation for swapping over to whatever the new terms are. A quick skim through the document reveals that RFC 7540 is at least fairly consistent with its use of the word payload. It's not perfect, but it's close.

The word "payload" appears 57 times in the current `main` revision. The first instance notes that the term "payload body" is defined in RFC 7230, which is nice. The other major usage forms are either "frame payload" or the composite phrase "payload of a * frame". We can treat that as another distinct item. We should consider whether the composite phrase "payload of a * frame" should be comprehensively rewritten to be "frame payload of a * frame".

Excluding those, there are only a few instances that need to be placed into one of these two buckets:

https://github.com/httpwg/http2-spec/blob/0277adffeb4dfa0b02608a1b88f0825e9a39feb7/draft-thomson-httpbis-http2bis.xml#L310

- This should probably be "HTTP/2 SETTINGS frame payload"

https://github.com/httpwg/http2-spec/blob/0277adffeb4dfa0b02608a1b88f0825e9a39feb7/draft-thomson-httpbis-http2bis.xml#L510

- Should be "frame payload"

https://github.com/httpwg/http2-spec/blob/0277adffeb4dfa0b02608a1b88f0825e9a39feb7/draft-thomson-httpbis-http2bis.xml#L595

- Should be "frame payload data"

https://github.com/httpwg/http2-spec/blob/0277adffeb4dfa0b02608a1b88f0825e9a39feb7/draft-thomson-httpbis-http2bis.xml#L1538-L1540

- Should be "request or response payload bodies" not "request or response payloads"

https://github.com/httpwg/http2-spec/blob/0277adffeb4dfa0b02608a1b88f0825e9a39feb7/draft-thomson-httpbis-http2bis.xml#L2191

- Should be "frame payload"

https://github.com/httpwg/http2-spec/blob/0277adffeb4dfa0b02608a1b88f0825e9a39feb7/draft-thomson-httpbis-http2bis.xml#L2195-L2197

- Should be "with an identical frame payload"

https://github.com/httpwg/http2-spec/blob/0277adffeb4dfa0b02608a1b88f0825e9a39feb7/draft-thomson-httpbis-http2bis.xml#L2380-L2381

- Should be "frame payload"

https://github.com/httpwg/http2-spec/blob/0277adffeb4dfa0b02608a1b88f0825e9a39feb7/draft-thomson-httpbis-http2bis.xml#L2725

- Probably the most egregious, given that we defined the term earlier, should be "payload bodies"

https://github.com/httpwg/http2-spec/blob/0277adffeb4dfa0b02608a1b88f0825e9a39feb7/draft-thomson-httpbis-http2bis.xml#L2960

- This citation uses "payload body" in the same paragraph, which is annoyingly inconsistent. Should be "a response that is defined to have no payload body".

https://github.com/httpwg/http2-spec/blob/0277adffeb4dfa0b02608a1b88f0825e9a39feb7/draft-thomson-httpbis-http2bis.xml#L3016

- Should be "payload body", not "payload data"

https://github.com/httpwg/http2-spec/blob/0277adffeb4dfa0b02608a1b88f0825e9a39feb7/draft-thomson-httpbis-http2bis.xml#L3047

- Should be "payload body", not "payload data"

https://github.com/httpwg/http2-spec/blob/0277adffeb4dfa0b02608a1b88f0825e9a39feb7/draft-thomson-httpbis-http2bis.xml#L3789-L3795

- Payload appears twice here: should be "frame payload".
